config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    def index
        @boards = Board.all
    end

    def new
        @board = Board.new
    end

    def create
        board = Board.new(board_params)
        if board.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @board = Board.find(params[:id])
    end

    def edit
        @board = Board.find(params[:id])
    end

    def update
        board = Board.find(params[:id])
        if Board.update(board_params)
            redirect_to :action => "show", :id => board.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        board = Board.find(params[:id])
        board.destroy
        redirect_to action: :index
    end
    
    private
    def board_params
        params.require(:board).permit(:body, :title, :subject, :grade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/edit.html.erb
<%= form_for @board do |f| %>
    <%= f.label :"投稿タイトル" %>
    <%= f.text_field :title , :size => 140 %><br>

    <%= f.label :"科目" %>
    <%= f.text_field :subject , :size => 140 %><br>

    <%= f.label :"学年" %>
    <%= f.text_field :grade , :size => 140 %><br>

    <%= f.label :"投稿内容" %>
    <%= f.text_field :body , :size => 140 %><br>
    <br>
    <%= f.submit "投稿する" %>
<% end %>

app/views/boards/index.html.erb
<head> 
<div class='apple'>
    <h1>AAA School</h1>
    <div class="buttom-box">
    <button type="button" class="btn">戻る</button>
    </div> 
</div>
</head>

<%# <header>
　　<div class="header-logo">
　　</div>
　　<div class="header-list">
　　　<ul>
　　　　<li>戻る</li>
　　　</ul>
　　</div>
　</header>
 <%>

<h3>投稿一覧</h3>
<%= link_to "新規投稿へ", new_board_path %>
<div class="boards-container">
<% @boards.each do |t| %>
    <div class="board">
        <b><%= t.title %></b>
        <p><%= t.subject %>
        <%= t.grade %></p>
        <%= t.body %>
        <%= t.created_at %>
        <%= link_to "詳細へ", board_path(t.id) %>
        <%= link_to "編集する", edit_board_path(t.id) %>
        <%= button_to "削除する", board_path(t.id), method: :delete %>
    </div>
<% end %>
</div>

app/views/boards/new.html.erb
<%= form_for @board do |f| %>
    <%= f.label :"投稿タイトル" %>
    <%= f.text_field :title , :size => 140 %><br>

    <%= f.label :"科目" %>
    <%= f.text_field :subject , :size => 140 %><br>

    <%= f.label :"学年" %>
    <%= f.text_field :grade , :size => 140 %><br>

    <%= f.label :"投稿内容" %>
    <%= f.text_field :body , :size => 140 %><br>
    <br>
    <%= f.submit "投稿する" %>
<% end %>

app/views/boards/show.html.erb
<h3>詳細</h3>
<div class="board">
    <b><%= @board.title %></b>
    <p><%= @board.subject %>
    <%= @board.grade %></p>
    <%= @board.body %>
    <p><%= @board.created_at %></p>
    <%= link_to "編集する", edit_board_path(@board.id) %>
</div>
<%= link_to "一覧に戻る", boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onestudy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>